name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  # flutter_native_splash: ^2.3.0
  bynd:
    path: Package/bynd


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  


# flutter_icons:
#   ios: true
#   android: true
#   image_path: "assets/marketing/app-icon-1024.png"

flutter:
  uses-material-design: true

  generate: true

  # assets:
  #   - assets/images
  
  # fonts:
  #   - family: Cinzel
  #     fonts:
  #       - asset: assets/fonts/CinzelDecorative-Regular.ttf